# Generated by Django 3.2.9 on 2021-11-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211122_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
